# Generated by Django 3.1.2 on 2020-10-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('phone_no', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
