# Generated by Django 3.1.2 on 2020-10-20 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0002_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_app.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Raw',
        ),
    ]
