# Generated by Django 3.1.2 on 2020-10-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0004_auto_20201020_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='add_user',
        ),
        migrations.AddField(
            model_name='group',
            name='add_user',
            field=models.ManyToManyField(to='dj_app.User'),
        ),
    ]
